archiv/urls.py
# generated by appcreator
from django.urls import path

from . import views

app_name = "archiv"
urlpatterns = [
    path("court/", views.CourtListView.as_view(), name="court_browse"),
    path("court/detail/<int:pk>", views.CourtDetailView.as_view(), name="court_detail"),
    path("court/create/", views.CourtCreate.as_view(), name="court_create"),
    path("court/edit/<int:pk>", views.CourtUpdate.as_view(), name="court_edit"),
    path("court/delete/<int:pk>", views.CourtDelete.as_view(), name="court_delete"),
    path("yearbook/", views.YearBookListView.as_view(), name="yearbook_browse"),
    path(
        "yearbook/detail/<int:pk>",
        views.YearBookDetailView.as_view(),
        name="yearbook_detail",
    ),
    path("yearbook/create/", views.YearBookCreate.as_view(), name="yearbook_create"),
    path(
        "yearbook/edit/<int:pk>", views.YearBookUpdate.as_view(), name="yearbook_edit"
    ),
    path(
        "yearbook/delete/<int:pk>",
        views.YearBookDelete.as_view(),
        name="yearbook_delete",
    ),
    path(
        "case/",
        views.CourtDecissionListView.as_view(),
        name="courtdecission_browse",
    ),
    path(
        "case/detail/<int:pk>",
        views.CourtDecissionDetailView.as_view(),
        name="courtdecission_detail",
    ),
    path(
        "case/create/",
        views.CourtDecissionCreate.as_view(),
        name="courtdecission_create",
    ),
    path(
        "case/edit/<int:pk>",
        views.CourtDecissionUpdate.as_view(),
        name="courtdecission_edit",
    ),
    path(
        "case/delete/<int:pk>",
        views.CourtDecissionDelete.as_view(),
        name="courtdecission_delete",
    ),
    path("keyword/", views.KeyWordListView.as_view(), name="keyword_browse"),
    path(
        "keyword/detail/<int:pk>",
        views.KeyWordDetailView.as_view(),
        name="keyword_detail",
    ),
    path("keyword/create/", views.KeyWordCreate.as_view(), name="keyword_create"),
    path("keyword/edit/<int:pk>", views.KeyWordUpdate.as_view(), name="keyword_edit"),
    path(
        "keyword/delete/<int:pk>", views.KeyWordDelete.as_view(), name="keyword_delete"
    ),
    path(
        "legalsystem/",
        views.PartialLegalSystemListView.as_view(),
        name="partiallegalsystem_browse",
    ),
    path(
        "legalsystem/detail/<int:pk>",
        views.PartialLegalSystemDetailView.as_view(),
        name="partiallegalsystem_detail",
    ),
    path(
        "legalsystem/create/",
        views.PartialLegalSystemCreate.as_view(),
        name="partiallegalsystem_create",
    ),
    path(
        "legalsystem/edit/<int:pk>",
        views.PartialLegalSystemUpdate.as_view(),
        name="partiallegalsystem_edit",
    ),
    path(
        "legalsystem/delete/<int:pk>",
        views.PartialLegalSystemDelete.as_view(),
        name="partiallegalsystem_delete",
    ),
    path("author/", views.PersonListView.as_view(), name="person_browse"),
    path(
        "author/detail/<int:pk>", views.PersonDetailView.as_view(), name="person_detail"
    ),
    path("author/create/", views.PersonCreate.as_view(), name="person_create"),
    path("author/edit/<int:pk>", views.PersonUpdate.as_view(), name="person_edit"),
    path("author/delete/<int:pk>", views.PersonDelete.as_view(), name="person_delete"),
    path("tag/", views.TagListView.as_view(), name="tag_browse"),
    path("tag/detail/<int:pk>", views.TagDetailView.as_view(), name="tag_detail"),
    path("tag/create/", views.TagCreate.as_view(), name="tag_create"),
    path("tag/edit/<int:pk>", views.TagUpdate.as_view(), name="tag_edit"),
    path("tag/delete/<int:pk>", views.TagDelete.as_view(), name="tag_delete"),
]

djangobaseproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("archive/", include("archiv.urls", namespace="archiv")),
    path("archiv-ac/", include("archiv.dal_urls", namespace="archiv-ac")),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("", include("webpage.urls", namespace="webpage")),
]
handler404 = "webpage.views.handler404"

webpage/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django_spaghetti.views import Plate

from . import views

app_name = "webpage"

favicon_view = RedirectView.as_view(url="/static/favicon.ico", permanent=True)

urlpatterns = [
    path("imprint", views.ImprintView.as_view(), name="imprint"),
    path("", views.GenericWebpageView.as_view(), name="start"),
    path(
        "data-model",
        Plate.as_view(plate_template_name="webpage/data_model.html"),
        name="data_model",
    ),
    path("accounts/login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="user_logout"),
    path("<slug:template>", views.GenericWebpageView.as_view(), name="staticpage"),
]

templates/partials/footer.html
{% load webpage_extras %}
{% load static %}

<footer class="py-3">
  <div class="container text-center">
    <div class="d-flex align-items-center gap-2 border-bottom pb-3 mb-4" style="color: #444;"><i class="bi bi-chat"
        style="font-size: 1.125rem;"></i><span class="fw-medium" style="font-size: 0.875rem;">Kontakt</span></div>
    <div class="row justify-content-md-center">
      <div class="col col-lg-4">
        <div><a href="https://www.oeaw.ac.at/acdh/acdh-home">
          <img class="footerlogo" src="{% static 'webpage/images/acdh-logo-with-text-color.svg' %}" alt="ACDH logo"></a></div>
        <div class="text-center p-4">
          ACDH Austrian Centre for Digital Humanities Österreichische
          Akademie der Wissenschaften
          <br><a href="mailto:acdh-helpdesk@oeaw.ac.at">acdh-helpdesk@oeaw.ac.at</a>
        </div>
      </div>
      <div class="col col-lg-4"></div>
      <div class="col col-lg-4">
        <div>
          <a href="https://www.oeaw.ac.at/etl"><img
              class="footerlogo" src="{% static 'webpage/images/etl-logo.svg' %}"
              alt="Institute for European Tort Law (ETL) logo"></a>
        </div>
        <div class="text-center p-4">
          Institute for European Tort Law (ETL) of the Austrian Academy of Sciences and the University of Graz
          <br><a href="mailto:etl@oeaw.ac.at">etl@oeaw.ac.at</a>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center">
    <a href="{% projects_metadata 'github' %}">
      <i aria-hidden="true" class="bi bi-github fs-2"></i>
      <span class="visually-hidden">GitHub repo</span>
    </a>
  </div>
</footer>

templates/partials/head.html
{% load static %}
{% load webpage_extras %}


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% block metaDescription %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<link
  rel="stylesheet"
  href="https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.1/dist/bootstrap-toc.min.css"
/>
<link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" />
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://matomo.acdh.oeaw.ac.at/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '240']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->

{% block scriptHeader %}
{% endblock scriptHeader %}

templates/partials/navbar.html
{% load static %}
{% load webpage_extras %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
             <a class="navbar-brand" href="/">
      <img src="{% static 'webpage/images/project-logo.gif' %}" alt="project-logo" width="35" height="35">
    </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fs-6" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Info
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'webpage:staticpage' template='about' %}">About the project</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'webpage:staticpage' template='search' %}">Search</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'webpage:data_model' %}">Data Model</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'webpage:staticpage' template='imprint' %}">Imprint</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fs-6" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Browse
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'archiv:courtdecission_browse' %}">Cases</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'archiv:court_browse' %}">Courts</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'archiv:partiallegalsystem_browse' %}">Legal
                                    systems</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'archiv:keyword_browse' %}">Keywords</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'archiv:tag_browse' %}">Tags</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'archiv:yearbook_browse' %}">Bibliographic
                                    items</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'archiv:person_browse' %}">Authors</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="text-end me-5">
                {% if user.is_authenticated %}
                <a href="{% url 'webpage:user_logout' %}">
                    <i class="bi bi-person-check fs-2">
                    <span class="visually-hidden">Click to log out</span></i>
                </a>
                {% else %}
                <a href="{% url 'webpage:user_login' %}">
                    <i class="bi bi-box-arrow-in-right fs-2"></i>
                    <span class="visually-hidden">Click to log in</span>
                </a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>